// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdvONpY0Jr7_kkXE0oOWLZBk5mRC9DnUA',
    appId: '1:186303062477:web:d32f186d622d667d1ca484',
    messagingSenderId: '186303062477',
    projectId: 'futsal-gembira-df88b',
    authDomain: 'futsal-gembira-df88b.firebaseapp.com',
    storageBucket: 'futsal-gembira-df88b.appspot.com',
    measurementId: 'G-Q79KK5ZFL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeSZOtjKV9wopKLQIVvIuNFU0Ikazb6o',
    appId: '1:186303062477:android:d84b4d9f10dc3b071ca484',
    messagingSenderId: '186303062477',
    projectId: 'futsal-gembira-df88b',
    storageBucket: 'futsal-gembira-df88b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYRaUfPA57agB-vJ4FhJCOxZFHyj2ZWA',
    appId: '1:186303062477:ios:2aa993bfba546ba91ca484',
    messagingSenderId: '186303062477',
    projectId: 'futsal-gembira-df88b',
    storageBucket: 'futsal-gembira-df88b.appspot.com',
    iosClientId: '186303062477-cj0t6a3tum3lotc161sc2ualuamofg12.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFutsalGembira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYRaUfPA57agB-vJ4FhJCOxZFHyj2ZWA',
    appId: '1:186303062477:ios:2aa993bfba546ba91ca484',
    messagingSenderId: '186303062477',
    projectId: 'futsal-gembira-df88b',
    storageBucket: 'futsal-gembira-df88b.appspot.com',
    iosClientId: '186303062477-cj0t6a3tum3lotc161sc2ualuamofg12.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFutsalGembira',
  );
}
